// Build script for sentinel-core.
//
// Compiles the Google Authenticator migration payload protobuf schema
// (proto/migration_payload.proto) into Rust types via prost-build.
//
// The .proto file is committed to the crate so the build is fully offline
// and reproducible — no network fetch at compile time.

use std::io::Write;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let proto_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let proto_path = format!("{proto_dir}/proto/migration_payload.proto");

    // Verify the proto file exists before attempting compilation.
    if !std::path::Path::new(&proto_path).exists() {
        let msg = format!(
            "migration_payload.proto not found at {proto_path}. \
             This file is required to compile sentinel-core."
        );
        println!("cargo:error={msg}");
        return Err(msg.into());
    }

    println!("cargo:rerun-if-changed={proto_path}");

    let mut config = prost_build::Config::new();
    config.out_dir(format!("{proto_dir}/src/proto/gen"));
    // Suppress clippy warnings on generated code (prost output is not hand-written).
    config.disable_comments(["."]);
    // We'll add `#![allow(...)]` to the generated file via a wrapper.

    config.compile_protos(&[&proto_path], &[&format!("{proto_dir}/proto")])?;

    // Prepend `#![allow(...)]` to the generated migration.rs to suppress
    // clippy/fmt warnings on prost output.
    let generated_path = format!("{proto_dir}/src/proto/gen/migration.rs");
    if std::path::Path::new(&generated_path).exists() {
        let content = std::fs::read_to_string(&generated_path)?;
        if !content.starts_with("#![allow(") {
            let allow_header = "#![allow(clippy::all, clippy::pedantic, clippy::nursery, dead_code, unused_imports)]\n";
            std::fs::write(&generated_path, format!("{allow_header}{content}"))?;
        }
    }

    // Also write a small module marker so the generated code can be included.
    let gen_marker = format!("{proto_dir}/src/proto/gen/mod.rs");
    if let Some(parent) = std::path::Path::new(&gen_marker).parent() {
        std::fs::create_dir_all(parent)?;
    }
    let mut f = std::fs::File::create(&gen_marker)?;
    writeln!(
        f,
        "// @generated by build.rs — do not edit. Prost output lives in sibling files."
    )?;
    writeln!(f, "// Includes the generated MigrationPayload type.")?;
    writeln!(f)?;
    writeln!(f, "pub mod migration;")?;

    Ok(())
}
